# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: gradle build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 11
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.11.1
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Execute Gradle build
      run: ./gradlew build
